"use client";
import { useRef, useState } from "react";

// Section 3 — how Starlane thinks. A keyboard-accessible tablist (arrow keys,
// Home/End) rather than an autoplaying carousel: the visitor controls pace.
// Each stage says what Starlane does AND what exists today, so the page never
// promises past the product.

const STAGES = [
  {
    key: "sources",
    label: "Sources",
    head: "It starts from your systems of record.",
    body: "Accounting, stock and banking data arrive through a local bridge, a file, or — as they are built — official APIs. External signals such as exchange rates and major earthquakes arrive from public feeds.",
    today: "TallyPrime via the local bridge. CSV and Excel exports from any system. Bank statement import. Public feeds: ECB exchange rates, USGS earthquakes.",
  },
  {
    key: "state",
    label: "State",
    head: "Everything is normalized into one business state.",
    body: "Vouchers become invoices, purchases, payments and stock movements. Every row keeps where it came from. Re-importing the same data changes nothing.",
    today: "Receivables, payables, bank movements, products and stock, customers and suppliers — with provenance and idempotent imports.",
  },
  {
    key: "dependencies",
    label: "Dependencies",
    head: "Then how the parts of the business depend on each other.",
    body: "Which products come from which suppliers, which open orders need them, which customers owe what. External events are matched to the entities they touch — not broadcast to everyone.",
    today: "Supplier → product → open-order links from purchase history; world events matched to supplier locations.",
  },
  {
    key: "paths",
    label: "Paths",
    head: "Credible actions are generated and ranked.",
    body: "For each situation Starlane considers a small set of real options — remind, escalate, reorder, wait — and ranks them by explicit rules and measured behaviour, not by a model’s preference.",
    today: "Collections stages by days overdue, adjusted by each customer’s recorded response to past reminders. Reorder suggestions from stock coverage. Cash scenarios over your real baseline.",
  },
  {
    key: "evidence",
    label: "Evidence",
    head: "Every recommendation carries its reasons.",
    body: "The facts it used, the rule it applied, and anything it had to assume — each labelled observed, calculated, assumed or forecast. Numbers are computed, never generated by a language model.",
    today: "Structured evidence on every collections recommendation: source row, amount, days overdue, stage band and why.",
  },
  {
    key: "action",
    label: "Action",
    head: "People approve. Then Starlane acts.",
    body: "Actions wait for a decision. The exact payload — recipient, message, quantities — is frozen when proposed, so what you approve is what runs. Each action executes at most once.",
    today: "Approve in the app or from a one-tap link that asks you to confirm. Reminders, purchase orders and calls where the channel is configured.",
  },
  {
    key: "verification",
    label: "Verification",
    head: "And checks what actually happened.",
    body: "The expected effect is recorded before execution and compared with what the next sync shows. Outcomes feed back into how the next decision is ranked.",
    today: "Payment after reminder, stock-out avoided or not; recorded per action and per customer.",
  },
] as const;

export function HowItThinks() {
  const [active, setActive] = useState(0);
  const tabs = useRef<Array<HTMLButtonElement | null>>([]);

  const focusTab = (i: number) => {
    const n = (i + STAGES.length) % STAGES.length;
    setActive(n);
    tabs.current[n]?.focus();
  };
  const onKey = (e: React.KeyboardEvent) => {
    if (e.key === "ArrowRight" || e.key === "ArrowDown") { e.preventDefault(); focusTab(active + 1); }
    if (e.key === "ArrowLeft" || e.key === "ArrowUp") { e.preventDefault(); focusTab(active - 1); }
    if (e.key === "Home") { e.preventDefault(); focusTab(0); }
    if (e.key === "End") { e.preventDefault(); focusTab(STAGES.length - 1); }
  };
  const s = STAGES[active];

  return (
    <div className="sl-think">
      <div role="tablist" aria-label="How Starlane thinks" aria-orientation="vertical" className="sl-think-tabs" onKeyDown={onKey}>
        {STAGES.map((st, i) => (
          <button
            key={st.key}
            ref={(el) => { tabs.current[i] = el; }}
            role="tab"
            id={`think-tab-${st.key}`}
            aria-selected={i === active}
            aria-controls={`think-panel-${st.key}`}
            tabIndex={i === active ? 0 : -1}
            className={`sl-think-tab${i === active ? " on" : ""}${i < active ? " past" : ""}`}
            onClick={() => setActive(i)}
          >
            <span className="sl-think-n">{String(i + 1).padStart(2, "0")}</span>
            {st.label}
          </button>
        ))}
      </div>
      <div
        role="tabpanel"
        id={`think-panel-${s.key}`}
        aria-labelledby={`think-tab-${s.key}`}
        className="sl-think-panel"
        key={s.key}
        tabIndex={0}
      >
        <h3 className="sl-h3 sl-think-head">{s.head}</h3>
        <p className="sl-p">{s.body}</p>
        <div className="sl-think-today">
          <span className="sl-eyebrow" style={{ marginBottom: 8 }}>Working today</span>
          <p className="sl-p">{s.today}</p>
        </div>
      </div>
    </div>
  );
}
