"use client";

// Shared pieces for the seven-surface panels. Display only: every number
// passed in was computed by the backend.

import React, { useCallback, useEffect, useState } from "react";
import { C, Pill } from "@/components/decisions/ui";
import { DecisionApiError } from "@/lib/decisions";

export function Panel({ title, subtitle, right, children }: { title: string; subtitle?: React.ReactNode; right?: React.ReactNode; children: React.ReactNode }) {
  return (
    <section className="rounded-lg fade-once" style={{ background: "var(--bg-elevated)", border: `1px solid ${C.card}`, padding: "20px 22px" }}>
      <div className="flex items-start justify-between gap-3 mb-3 flex-wrap">
        <div style={{ minWidth: 0 }}>
          <h2 style={{ color: C.ink, fontFamily: "var(--font-sans)", fontWeight: 600, fontSize: 17, letterSpacing: "-0.015em", margin: 0 }}>{title}</h2>
          {subtitle && <p className="text-[12.5px] mt-1 leading-[1.55]" style={{ color: C.muted }}>{subtitle}</p>}
        </div>
        {right}
      </div>
      {children}
    </section>
  );
}

export function Btn({ children, onClick, primary, danger, disabled, type = "button", title }: { children: React.ReactNode; onClick?: () => void; primary?: boolean; danger?: boolean; disabled?: boolean; type?: "button" | "submit"; title?: string }) {
  return (
    <button
      type={type}
      onClick={onClick}
      disabled={disabled}
      title={title}
      className={`text-[12.5px] rounded-md px-3 py-[6px] whitespace-nowrap ${disabled ? "" : primary ? "btn-primary-v32" : "btn-secondary-v32"}`}
      style={{
        fontWeight: 400,
        cursor: disabled ? "default" : "pointer",
        opacity: disabled ? 0.4 : 1,
        color: primary ? "var(--text-on-inverse)" : danger ? C.bad : C.body,
        background: primary ? "var(--bg-inverse)" : "transparent",
        border: `1px solid ${primary ? "var(--text-primary)" : danger ? "rgba(166,79,75,0.35)" : "rgb(var(--c-ink) / 0.14)"}`,
      }}
    >
      {children}
    </button>
  );
}

export function Row({ children }: { children: React.ReactNode }) {
  return <div className="py-3.5" style={{ borderTop: `1px solid ${C.line}` }}>{children}</div>;
}

export function Muted({ children }: { children: React.ReactNode }) {
  return <p className="text-[12.5px] leading-[1.55]" style={{ color: C.muted }}>{children}</p>;
}

export function ErrorLine({ error }: { error: string | null }) {
  if (!error) return null;
  return <p className="text-[12.5px] mt-2" role="alert" style={{ color: C.bad }}>{error}</p>;
}

export function errorText(err: unknown): string {
  return err instanceof Error ? err.message : "Something went wrong.";
}

/**
 * True only when the backend says its tables are not there yet (it sends a
 * *_NOT_MIGRATED code) or the route does not exist. Any other 5xx is an
 * outage and is shown as an error, not as "not set up".
 */
export function isNotReady(err: unknown): boolean {
  if (!(err instanceof DecisionApiError)) return false;
  const code = typeof err.body?.code === "string" ? err.body.code : "";
  return err.status === 404 || code.endsWith("_NOT_MIGRATED");
}

export function healthTone(h?: string | null): "good" | "warn" | "bad" | "neutral" {
  if (h === "ON_TRACK" || h === "CONNECTED") return "good";
  if (h === "AT_RISK" || h === "DEGRADED" || h === "RATE_LIMITED") return "warn";
  if (h === "OFF_TRACK" || h === "STALE" || h === "FAILED" || h === "AUTH_EXPIRED" || h === "DISCONNECTED") return "bad";
  return "neutral";
}

export function ScoreBar({ value }: { value: number }) {
  const w = Math.max(0, Math.min(1, value)) * 100;
  return (
    <div className="h-[6px] rounded-full w-full" style={{ background: "#EFEFEC" }} aria-hidden>
      <div className="h-[6px] rounded-full" style={{ width: `${w}%`, background: C.accent }} />
    </div>
  );
}

export function FixtureAware({ names }: { names: string[] }) {
  // Names generated by the fixture ledger end in "(Fixture)". Say so plainly.
  if (!names.some((n) => /\(Fixture\)/.test(n))) return null;
  return <Pill tone="warn">Fixture data, not a real business</Pill>;
}

/** Load once on mount, with a manual reload. */
export function useLoad<T>(fn: () => Promise<T>) {
  const [data, setData] = useState<T | null>(null);
  const [error, setError] = useState<unknown>(null);
  const [loading, setLoading] = useState(true);
  const reload = useCallback(async () => {
    setLoading(true);
    try {
      setData(await fn());
      setError(null);
    } catch (err) {
      setError(err);
    } finally {
      setLoading(false);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  useEffect(() => { reload(); }, [reload]);
  return { data, error, loading, reload, setData };
}

/**
 * The amount a decision puts at stake, by name. A threshold, share or
 * probability is never shown as the money at stake.
 */
export function stakeOf(materiality?: Record<string, unknown> | null): number | null {
  if (!materiality) return null;
  for (const k of ["expectedUncollected90", "workingCapitalTiedUp", "revenueExposure"]) {
    const v = materiality[k];
    if (typeof v === "number" && Number.isFinite(v) && v > 0) return v;
  }
  return null;
}
