// Builds every Starlane brand asset from the two outlined masters in brand/:
//   brand/starlane-s.svg          the S monogram (Playfair Display Bold, SIL OFL)
//   brand/starlane-wordmark.svg   "Starlane" in the same face
//
//   node scripts/make-brand.mjs            web + mobile + desktop icon source
//   cd desktop && npm run icons            then regenerates the Tauri icon set
//
// One mark everywhere: an off-white S on the dark rail colour, or the reverse on
// light surfaces. Requires sharp (a root dependency).
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import sharp from 'sharp';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const at = (p) => path.join(ROOT, p);

const RAIL = '#1B1B18';
const INK = '#F2F1EC';
const LIGHT = '#F7F7F4';

const pathOf = (file) => readFileSync(at(file), 'utf8').match(/ d="([^"]+)"/)[1];
const viewBoxOf = (file) => readFileSync(at(file), 'utf8').match(/viewBox="([^"]+)"/)[1].split(' ').map(Number);
const S = pathOf('brand/starlane-s.svg'); // 1000 x 1000, cap height = 1000
const WORD = pathOf('brand/starlane-wordmark.svg');
const [, , WORD_W, WORD_H] = viewBoxOf('brand/starlane-wordmark.svg');

// The S sits optically high in a serif face; nudge it down by 1% of the glyph.
function glyph(cx, cy, h, fill) {
  const k = h / 1000;
  return `<path transform="translate(${cx - 500 * k} ${cy - 500 * k + h * 0.01}) scale(${k})" d="${S}" fill="${fill}"/>`;
}

// size: canvas px. tile: background colour or null (transparent). glyphH: S height as a share of
// the canvas. radius/margin: rounded-square tile as a share of the canvas (radius 0 = full bleed).
function svg(size, { tile = RAIL, ink = INK, glyphH = 0.5, radius = 0, margin = 0 } = {}) {
  const m = size * margin, w = size - 2 * m;
  const bg = tile ? `<rect x="${m}" y="${m}" width="${w}" height="${w}" rx="${size * radius}" fill="${tile}"/>` : '';
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">${bg}${glyph(size / 2, size / 2, size * glyphH, ink)}</svg>`;
}

function wordmarkSvg(width, height, { bg = null, ink = INK, textW = 0.7 } = {}) {
  const k = (width * textW) / WORD_W;
  const x = (width - WORD_W * k) / 2, y = (height - WORD_H * k) / 2;
  const back = bg ? `<rect width="${width}" height="${height}" fill="${bg}"/>` : '';
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">${back}<path transform="translate(${x} ${y}) scale(${k})" d="${WORD}" fill="${ink}"/></svg>`;
}

async function png(file, svgText, opts = {}) {
  let img = sharp(Buffer.from(svgText), { density: 300 }).resize(opts.width, opts.height);
  img = opts.jpeg ? img.flatten({ background: opts.flatten || RAIL }).jpeg({ quality: 92 }) : img.png();
  await img.toFile(at(file));
  console.log(file);
}

// Web app ------------------------------------------------------------------
const tileSvg100 = svg(100, { glyphH: 0.56, radius: 0.22 });
writeFileSync(at('public/icon.svg'), tileSvg100 + '\n');
writeFileSync(at('logo.svg'), tileSvg100 + '\n');
for (const n of [192, 512]) await png(`public/icon-${n}.png`, svg(n, { glyphH: 0.5, radius: 0.22 }));
for (const n of [180, 192, 512]) await png(`public/branding/starlane-icon-light-${n}.png`, svg(n, { tile: LIGHT, ink: RAIL, glyphH: 0.5 }));
await png('public/branding/starlane-mark.png', svg(1254, { glyphH: 0.5 }));
await png('public/brand/starlane-icon.jpeg', svg(1254, { glyphH: 0.5 }), { jpeg: true });
await png('public/brand/starlane-icon-transparent.png', svg(662, { tile: null, ink: RAIL, glyphH: 0.9 }), { width: 872, height: 662 });
await png('public/branding/starlane-wordmark.png', wordmarkSvg(2172, 724, { bg: RAIL, textW: 0.62 }));
await png('public/brand/starlane-wordmark.jpeg', wordmarkSvg(1600, 900, { bg: RAIL, textW: 0.62 }), { jpeg: true });

// Open Graph lockup: black wordmark on transparent, inlined for the edge renderer.
{
  const w = 620, h = Math.round(620 * WORD_H / WORD_W);
  const buf = await sharp(Buffer.from(wordmarkSvg(w * 2, h * 2, { ink: '#000000', textW: 1 }))).resize(w * 2, h * 2).png().toBuffer();
  writeFileSync(at('app/og-wordmark.ts'),
    `// The Starlane wordmark (brand/starlane-wordmark.svg), black on transparent, at 2x.\n` +
    `// Inlined as a data URI so the OG renderer needs no filesystem or network access\n` +
    `// at request time. Regenerated by scripts/make-brand.mjs.\n` +
    `export const STARLANE_WORDMARK = "data:image/png;base64,${buf.toString('base64')}";\n` +
    `export const STARLANE_WORDMARK_SIZE = { width: ${w}, height: ${h} };\n`);
  console.log('app/og-wordmark.ts');
}

// Mobile (Expo) ---------------------------------------------------------------
await png('mobile/assets/icon.png', svg(1024, { glyphH: 0.5 }));                              // iOS: opaque, full bleed
await png('mobile/assets/android-icon-foreground.png', svg(1024, { tile: null, glyphH: 0.36 })); // inside the 66% safe zone
await png('mobile/assets/android-icon-monochrome.png', svg(1024, { tile: null, ink: '#FFFFFF', glyphH: 0.36 }));
await png('mobile/assets/splash-icon.png', svg(512, { tile: null, glyphH: 0.7 }));
await png('mobile/assets/favicon.png', svg(48, { glyphH: 0.62, radius: 0.22 }));

// Desktop (Tauri) -------------------------------------------------------------
await png('desktop/icon-source.png', svg(1024, { glyphH: 0.5, radius: 0.2, margin: 0.06 }));   // `tauri icon` input
await png('desktop/public/favicon.png', svg(32, { glyphH: 0.62, radius: 0.22 }));
